Add simple kustomization validation jobs
Change-Id: I42f63c43e688f39e79b5fab425aeebcc3bf3c236

diff --git a/builder-macros.yaml b/builder-macros.yaml
--- a/builder-macros.yaml
+++ b/builder-macros.yaml
@@ -271,6 +271,22 @@
          helm push *.tgz oci://registry.rc.nectar.org.au/nectar-helm
 
 - builder:
+    name: kustomize-validate
+    builders:
+      - shell: |
+         #!/bin/bash
+         kustomizatons=$(find . -name kustomization.yaml -print0 | xargs -0 -n1 dirname | sort --unique)
+         for kustomization in ${kustomizatons}; do
+           if kustomize build "${kustomization}" -o /tmp/manifest.yaml; then
+             echo "validated ${kustomization}"
+           else
+             echo "validation failed for ${kustomization}"
+             exit 1
+           fi
+         done
+
+
+- builder:
     name: markdown-lint
     builders:
       - shell: |
